// apps/portfolio/components/ThemeSelector.tsx
import { Menu, Transition } from '@headlessui/react';
import { useTheme } from 'next-themes';
import { Fragment, useCallback } from 'react';
import classNames from 'classnames';
import {
  DesktopComputerIcon,
  MoonIcon,
  SunIcon,
} from '@heroicons/react/outline';

export function ThemeSelector({ className }: { className?: string }) {
  const { theme, resolvedTheme, setTheme } = useTheme();
  const activateMode = useCallback(
    (mode: string) => {
      setTheme(mode);
    },
    [setTheme]
  );

  return (
    <Menu as="div" className="relative">
      <Menu.Button
        className={classNames(
          'flex items-center text-sm focus:outline-none lg:rounded-md',
          className
        )}
      >
        <span
          className={classNames('block text-sm font-medium', {
            'hover:text-on-background text-neutral-500': theme === 'system',
            'text-primary': theme !== 'system',
          })}
        >
          <span className="sr-only">Open theme menu</span>
          {resolvedTheme === 'light' ? (
            <SunIcon className="h-6 w-6" aria-hidden="true" />
          ) : (
            <MoonIcon className="h-6 w-6" aria-hidden="true" />
          )}
        </span>
      </Menu.Button>
      <Transition
        as={Fragment}
        enter="transition ease-out duration-100"
        enterFrom="transform opacity-0 scale-95"
        enterTo="transform opacity-100 scale-100"
        leave="transition ease-in duration-75"
        leaveFrom="transform opacity-100 scale-100"
        leaveTo="transform opacity-0 scale-95"
      >
        <Menu.Items className="bg-surface absolute right-0 z-50 mt-2 w-48 origin-top-right rounded-md py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none dark:shadow-black dark:ring-opacity-50">
          <Menu.Item>
            {({ active }) => (
              <button
                className={classNames(
                  active ? 'bg-neutral-400/20 dark:bg-neutral-100/20' : '',
                  'flex w-full items-center px-4 py-2 text-sm'
                )}
                onClick={() => activateMode('light')}
              >
                <SunIcon
                  className="mr-4 h-5 w-5 flex-shrink-0"
                  aria-hidden="true"
                />
                Light
              </button>
            )}
          </Menu.Item>
          <Menu.Item>
            {({ active }) => (
              <button
                className={classNames(
                  active ? 'bg-neutral-400/20 dark:bg-neutral-100/20' : '',
                  'flex w-full items-center px-4 py-2 text-sm'
                )}
                onClick={() => activateMode('dark')}
              >
                <MoonIcon
                  className="mr-4 h-5 w-5 flex-shrink-0"
                  aria-hidden="true"
                />
                Dark
              </button>
            )}
          </Menu.Item>
          <Menu.Item>
            {({ active }) => (
              <button
                className={classNames(
                  active ? 'bg-neutral-400/20 dark:bg-neutral-100/20' : '',
                  'flex w-full items-center px-4 py-2 text-sm'
                )}
                onClick={() => activateMode('system')}
              >
                <DesktopComputerIcon
                  className="mr-4 h-5 w-5 flex-shrink-0"
                  aria-hidden="true"
                />
                System
              </button>
            )}
          </Menu.Item>
        </Menu.Items>
      </Transition>
    </Menu>
  );
}

// apps/portfolio-angular/src/app/components/theme-selector/theme-selector.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'jr-theme-selector',
  templateUrl: './theme-selector.component.html',
  styleUrls: ['./theme-selector.component.css'],
})
export class ThemeSelectorComponent implements OnInit {
  theme = 'system';
  resolvedTheme = 'light';

  ngOnInit() {
    this.resolveTheme();
  }

  activateMode(mode: string) {
    switch (mode) {
      case 'light':
        // Whenever the user explicitly chooses light mode
        localStorage.setItem('theme', 'light');
        break;
      case 'dark':
        // Whenever the user explicitly chooses dark mode
        localStorage.setItem('theme', 'dark');
        break;
      default:
        // Whenever the user explicitly chooses to respect the OS preference
        localStorage.removeItem('theme');
        break;
    }

    this.resolveTheme();
  }

  private resolveTheme() {
    this.theme = localStorage.getItem('theme') || 'system';

    if (
      localStorage.getItem('theme') === 'dark' ||
      (!('theme' in localStorage) &&
        window.matchMedia('(prefers-color-scheme: dark)').matches)
    ) {
      this.resolvedTheme = 'dark';
      document.documentElement.classList.toggle('dark', true);
      document.documentElement.classList.toggle('light', false);
    } else {
      this.resolvedTheme = 'light';
      document.documentElement.classList.toggle('dark', false);
      document.documentElement.classList.toggle('light', true);
    }
  }
}

<div class="relative">
  <button
    class="flex items-center px-4 text-sm focus:outline-none lg:rounded-md lg:pr-0"
    [matMenuTriggerFor]="menu"
  >
    <span
      class="text-primary block text-sm font-medium"
      [class.!text-neutral-500]="theme === 'system'"
      [class.hover:!text-on-background]="theme === 'system'"
    >
      <span class="sr-only">Open theme menu</span>
      <svg
        *ngIf="resolvedTheme === 'light'"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="2"
        stroke="currentColor"
        aria-hidden="true"
        class="h-6 w-6"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
        ></path>
      </svg>
      <svg
        *ngIf="resolvedTheme === 'dark'"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="2"
        stroke="currentColor"
        aria-hidden="true"
        class="h-6 w-6"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
        ></path>
      </svg>
    </span>
  </button>

  <mat-menu
    #menu="matMenu"
    class="bg-surface absolute right-4 z-50 mt-2 w-48 origin-top-right rounded-md text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none dark:shadow-black dark:ring-opacity-50 lg:right-0"
  >
    <button
      class="flex w-full items-center px-4 py-2 text-sm hover:bg-neutral-400/20 hover:dark:bg-neutral-100/20"
      (click)="activateMode('light')"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="2"
        stroke="currentColor"
        aria-hidden="true"
        class="mr-4 h-5 w-5 flex-shrink-0"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
        ></path>
      </svg>
      Light
    </button>
    <button
      class="flex w-full items-center px-4 py-2 text-sm hover:bg-neutral-400/20 hover:dark:bg-neutral-100/20"
      (click)="activateMode('dark')"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="2"
        stroke="currentColor"
        aria-hidden="true"
        class="mr-4 h-5 w-5 flex-shrink-0"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
        ></path>
      </svg>
      Dark
    </button>
    <button
      class="flex w-full items-center px-4 py-2 text-sm hover:bg-neutral-400/20 hover:dark:bg-neutral-100/20"
      (click)="activateMode('system')"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="2"
        stroke="currentColor"
        aria-hidden="true"
        class="mr-4 h-5 w-5 flex-shrink-0"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
        ></path>
      </svg>
      System
    </button>
  </mat-menu>
</div>
